### ISSUE TITLE
GCDWebDAVServer doesn't work with CarotDAV

### ISSUE THREAD

**Issue by SevenSystems** [swisspol/GCDWebServer#344]
Well, it kind of works, but after the transfer, there's an error (which can be ignored, but of course isn't "nice" ;))

Rei.Fs.SimpleWebException: The remote server returned an error: (501) Not Implemented.
   at Rei.Fs.Webdav.WebdavFs.GetResponse(HttpWebRequest request, Boolean notreqstream)
   at Rei.Fs.Webdav.WebdavFs.SetProperties(ResourceId id, ResourceProperties prop)
   at CarotDAV.CacheManager.SetProperties(FsBase fs, ResourceId id, ResourceProperties prop)
   at CarotDAV.AsyncCopy.Worker_Upload_UploadFile(Task task1)

**Comment by swisspol** [comment]
What’s is CarotDAV?

**Comment by mattbewills** [comment]
CarotDAV.CacheManager.SetProperties(FsBase

**Comment by mattbewills** [comment]
Lol
